apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: acrexpertlivedevuksouth.azurecr.io/image-workflow-1694270236735:latest
          ports:
            - containerPort: 80